#!/usr/bin/env bash
# Validate Terraform for a request: fmt, validate, tflint, plan.
set -euo pipefail

REQUEST="${1:?Usage: validate-request.sh <request-id>}"
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REQ_DIR="${ROOT_DIR}/requests/${REQUEST}"
TF_DIR="${REQ_DIR}/03-terraform"
REPORT="${REQ_DIR}/04-validation/report.md"
TMP_PLAN="${REQ_DIR}/04-validation/plan.out"

VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8200}"
VAULT_TOKEN="${VAULT_TOKEN:-root}"

log() { echo "[validate] $*"; }
die() { echo "[validate] ERROR: $*" >&2; exit 1; }

[ -d "${TF_DIR}" ] || die "Terraform directory not found: ${TF_DIR}"
[ -f "${TF_DIR}/main.tf" ] || die "main.tf not found in ${TF_DIR}"

mkdir -p "${REQ_DIR}/04-validation"

# Ensure Vault port-forward when platform is bootstrapped
if [ -f "${ROOT_DIR}/.platform-state" ]; then
  "${ROOT_DIR}/scripts/ensure-vault-ready.sh" >/dev/null 2>&1 || true
fi

# Run phase order check
"${ROOT_DIR}/scripts/check-phase-order.sh" "${REQUEST}" || true

FMT_RESULT="SKIP"
VALIDATE_RESULT="SKIP"
TFLINT_RESULT="SKIP"
PLAN_RESULT="SKIP"
PLAN_SUMMARY=""
VERDICT="FAIL"

cd "${TF_DIR}"

log "Running terraform fmt -check..."
if terraform fmt -check -recursive . 2>/dev/null; then
  FMT_RESULT="PASS"
else
  FMT_RESULT="FAIL"
  log "Running terraform fmt to fix formatting..."
  terraform fmt -recursive .
  FMT_RESULT="PASS (auto-fixed)"
fi

log "Running terraform init..."
terraform init -backend=false -input=false >/dev/null

log "Running terraform validate..."
if terraform validate; then
  VALIDATE_RESULT="PASS"
else
  VALIDATE_RESULT="FAIL"
fi

if command -v tflint >/dev/null 2>&1; then
  log "Running tflint..."
  if tflint --init >/dev/null 2>&1 && tflint; then
    TFLINT_RESULT="PASS"
  else
    TFLINT_RESULT="FAIL"
  fi
else
  TFLINT_RESULT="SKIP (not installed)"
fi

if curl -sf "${VAULT_ADDR}/v1/sys/health" >/dev/null 2>&1; then
  log "Running terraform plan against ${VAULT_ADDR}..."
  export VAULT_ADDR VAULT_TOKEN
  if terraform plan -input=false -no-color -out="${TMP_PLAN}.tfplan" > "${TMP_PLAN}" 2>&1; then
    PLAN_RESULT="PASS"
    PLAN_SUMMARY="$(tail -20 "${TMP_PLAN}")"
  else
    PLAN_RESULT="FAIL"
    PLAN_SUMMARY="$(cat "${TMP_PLAN}")"
  fi
else
  PLAN_RESULT="SKIP (Vault unreachable at ${VAULT_ADDR})"
  PLAN_SUMMARY="Run 'make bootstrap && make platform-apply' to enable plan validation."
fi

if [[ "${FMT_RESULT}" == PASS* ]] && [[ "${VALIDATE_RESULT}" == "PASS" ]] \
   && [[ "${TFLINT_RESULT}" != "FAIL" ]]; then
  if [[ "${PLAN_RESULT}" == "PASS" ]]; then
    VERDICT="PASS"
  elif [[ "${PLAN_RESULT}" == SKIP* ]]; then
    VERDICT="PASS (plan skipped — Vault unavailable)"
  fi
fi

TIMESTAMP="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

cat > "${REPORT}" <<EOF
# Validation Report

| Field | Value |
|-------|-------|
| **Jira ticket** | ${REQUEST%%-*} |
| **Request** | ${REQUEST} |
| **Generated by** | \`scripts/validate-request.sh\` |
| **Timestamp** | ${TIMESTAMP} |
| **Status** | ${VERDICT} |

## Results

| Check | Result | Notes |
|-------|--------|-------|
| \`terraform fmt -check\` | ${FMT_RESULT} | |
| \`terraform validate\` | ${VALIDATE_RESULT} | |
| \`tflint\` | ${TFLINT_RESULT} | |
| \`terraform plan\` | ${PLAN_RESULT} | Vault: ${VAULT_ADDR} |

## Plan summary

\`\`\`
${PLAN_SUMMARY}
\`\`\`

## Verdict

- $([[ "${VERDICT}" == PASS* ]] && echo "[x]" || echo "[ ]") PASS — proceed to Bugbot review
- $([[ "${VERDICT}" != PASS* ]] && echo "[x]" || echo "[ ]") FAIL — fix issues before review
EOF

log "Report written to ${REPORT}"
log "Verdict: ${VERDICT}"

[[ "${VERDICT}" == PASS* ]] || exit 1
